repos:
  - repo: local
    hooks:
      - id: check-commit-message
        name: Check Conventional Commit Messages
        entry: python .git-hooks/check_commit_message.py
        language: system
        stages: [commit-msg]
